language: php

sudo: false

addons:
  apt:
    packages:
      - libxml2-utils

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - typo3@evoweb.de

# This is executed for all stages
before_install:
  - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  #- composer require phwoolcon/ci-pecl-cacher -n
  #- rm composer.lock
  # Cache till new version
  #- .Build/bin/ci-pecl-install swoole

install:
  - export TYPO3_PATH_WEB=$PWD/.Build/Web;
  - |
    composer require typo3/cms-core="$TYPO3_VERSION" $PREFER_LOWEST;
    if [ ! -z "$TESTING_FRAMEWORK" ]; then composer require --dev typo3/testing-framework="$TESTING_FRAMEWORK"; fi;
  - git checkout composer.json;

script:
  - >
    echo "Running ${TYPO3_VERSION} unit tests";
    php .Build/Web/vendor/bin/phpunit --colors -c .Build/Web/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit/;
    echo "Running $TYPO3_VERSION functional tests";
    export typo3DatabaseDriver="pdo_sqlite";
    php .Build/Web/vendor/bin/phpunit --colors -c .Build/Web/vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml Tests/Functional/;

jobs:
  allow_failures:
    - env: TYPO3_VERSION="dev-master as 10.4.0" TESTING_FRAMEWORK="^6.2.3"

  include:
    - stage: test
      php: 7.2
      env: TASK="XML Lint (Xliff)"
      before_install: skip
      install: skip
      before_script: skip
      script:
        - |
          echo "Running xmllint (Xliff)";
          find Resources/Private/Language/ -name '*.xlf' -type f | xargs xmllint --noout --schema .Build/xliff-core-1.2-strict.xsd

    - &lint
      stage: test
      php: 7.4
      env: TASK="PHP Lint"
      install: skip
      script:
        - |
          echo "Running php lint";
          errors=$(find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} 2>&1 >/dev/null \;) && echo "$errors" && test -z "$errors"
    - <<: *lint
      php: 7.3
    - <<: *lint
      php: 7.2

    - stage: test
      php: 7.4
      env: TYPO3_VERSION=^10.4 TESTING_FRAMEWORK="^6.2.3"
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=^10.4 TESTING_FRAMEWORK="^6.2.3"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^10.4 TESTING_FRAMEWORK="^6.2.3"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^10.4 TESTING_FRAMEWORK="^5.0.15" PREFER_LOWEST="--prefer-lowest"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="dev-master as 10.4.0" TESTING_FRAMEWORK="^6.2.3"

    - stage: publish in ter
      if: tag IS present
      php: 7.2
      before_install: skip
      install: skip
      script:
        - |
          if [[ "$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";

            # Install requirements
            composer global require helhum/ter-client

            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx

            # Set version number from tag
            sed -i "s/version' => '.*'/version' => '${TRAVIS_TAG}'/" ext_emconf.php

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload sf_register . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
